version: "3.9"

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: restaurant   
    volumes:
      - mongo_data:/data/db 
    ports:
      - "27017:27017"
  restaurant:
    build: .
    env_file: .env
    depends_on: [mongo]
    ports: ["3000:3000"]
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  mongo_data: